export const img: string;
export const credit_box: string;
export const creditBox: string;
export const credit_num: string;
export const creditNum: string;
export const credit_num_suffix: string;
export const creditNumSuffix: string;
export const credit_add: string;
export const creditAdd: string;
